# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180204_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 4, 18, 28, 37, 214928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 4, 18, 28, 37, 214428, tzinfo=utc)),
        ),
    ]
