# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-14 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180314_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 1, 28, 5, 943407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 1, 28, 5, 942902, tzinfo=utc)),
        ),
    ]
